### ISSUE TITLE
Device Panel is not full screen on iPads.

### ISSUE THREAD

**Issue by gokselsina** [tuya/tuya-bizbundle-ios-sdk-sample-objc#13]
![WhatsApp Image 2023-10-18 at 16 16 24](https://github.com/tuya/tuya-bizbundle-ios-sdk-sample-objc/assets/115628199/040da575-f2c9-45b9-a313-6418ce2be7f5)
![WhatsApp Image 2023-10-18 at 16 16 24-2](https://github.com/tuya/tuya-bizbundle-ios-sdk-sample-objc/assets/115628199/bb009032-a23c-42be-97b5-9da6b2ffd20f)

**Comment by taojingGino** [comment]
device panel not support full screen
you can use
     id<ThingPanelProtocol> impl = [[ThingSmartBizCore sharedInstance] serviceOfProtocol:@protocol(ThingPanelProtocol)];
    [impl gotoPanelViewControllerWithDevice:deviceModel group:nil initialProps:nil contextProps:nil completion:^(NSError * _Nullable error) {
        
    }];

and it will be like this

<img width="540" alt="企业微信截图_ebb528fe-53d6-4eba-9c7c-a250a222d3cc" src="https://github.com/tuya/tuya-bizbundle-ios-sdk-sample-objc/assets/59640671/fe957d5b-3ca7-4833-ac1b-6e874423f809">
@gokselsina
