### ISSUE TITLE
IPC Panel does not work

### ISSUE THREAD

**Issue by tanshuai** [tuya/tuya-bizbundle-ios-sdk-sample-objc#2]
Use the latest code of this repo, successfully compiled and run on iPhone 12 Pro Max (iOS 14.6).

1. Enter the [IPC Panel] menu, select "Online" or "Offline" of camera devices.
2. Show [Please select the bell type] UI page, select either type of bell then press the [Complete] button.
3. Wait for moment and finally display "Request timed out" message.
3. No matter how to operates, this sample app can't show the IPC camera live video preview UI. 

The Android sample repo which is provided by Tuya did not have this problem with our camera devices.

![EB365B6E-6005-4F58-932E-C39CA29AED5B_1_105_c](https://user-images.githubusercontent.com/3947852/126782839-dbf87a83-9090-43da-8a2a-e474d508f058.jpeg)
![88E7D05D-BB4A-442A-8961-8AF7387FEDFC_1_105_c](https://user-images.githubusercontent.com/3947852/126782844-8fbe7965-d16e-46eb-bc6b-76a58420904c.jpeg)
![image](https://user-images.githubusercontent.com/3947852/126782950-61f3365b-8ae6-4342-a0ed-7ca6de9af1c7.png)
![image](https://user-images.githubusercontent.com/3947852/126782970-408e2b62-27db-4c31-a691-9b6285be8c01.png)

**Comment by xiaoxuan-Tuya** [comment]
Hi , tanshuai 

Thank you for your feedback . Could you please provide the product ID of the device which couldn't work as expected? We will check it as soon as possible . By the way , since it works fine on Android sample .Could you provide a screenshot of the Preview UI on Android ?

**Comment by tanshuai** [comment]
@xiaoxuan-Tuya 

I solved this issue with a workaround by temporary disable the DP id "165".

Thank you for your support.
