### ISSUE TITLE
IPC panel crashed on Simulator: Thread 57: EXC_BAD_ACCESS (code=EXC_I386_GPFLT)

### ISSUE THREAD

**Issue by tanshuai** [tuya/tuya-bizbundle-ios-sdk-sample-objc#5]
Works on real iOS devices, but crashed on Simulator of Xcode with error "Thread 57: EXC_BAD_ACCESS (code=EXC_I386_GPFLT)".

<img width="1424" alt="xcode" src="https://user-images.githubusercontent.com/3947852/141440974-22da1b0e-ddab-4d7f-849d-23054dbb634e.png">

https://user-images.githubusercontent.com/3947852/141441407-bd338e1a-d7fb-42c2-ac71-d3777ebdc474.mov

https://user-images.githubusercontent.com/3947852/141442793-223d9c65-403c-4be4-9c16-bc42c74a9875.mov

[Podfile.lock.zip](https://github.com/tuya/tuya-bizbundle-ios-sdk-sample-objc/files/7526375/Podfile.lock.zip)

**Comment by taojingGino** [comment]
id<TYPanelProtocol> impl = [[TuyaSmartBizCore sharedInstance] serviceOfProtocol:@protocol(TYPanelProtocol)];
[impl getPanelViewControllerWithDeviceModel:deviceModel initialProps:nil contextProps:nil completionHandler:^(__kindof UIViewController * _Nullable panelViewController, NSError * _Nullable error) {
    [self.navigationController pushViewController:panelViewController animated:YES];
}];

add CameraBizBundle pod and than use TYPanelProtocol getPanelViewControllerWithDeviceModel，it support normal device and IPC device. We will fix the sample
